workspace:
  base: /go
  path: src/github.com/airwallex/drone-docker

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go vet ./...
      - go test -cover ./...
      - sh .drone.sh

  publish:
    image: plugins/docker
    repo: registry.airwallex.com/drone-docker
    tags:
      - ${DRONE_REPO_BRANCH//\//-}
      - ${DRONE_REPO_BRANCH//\//-}-${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch:
        exclude: [ master ]
      event: push

  publish:
    image: plugins/docker
    repo: registry.airwallex.com/drone-docker
    tags:
      - lastest
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push
